version: '3'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  db1:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  db2:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  db3:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  postgres_data:
